# Generated by Django 5.0.3 on 2024-03-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_first_name', models.CharField(max_length=100)),
                ('player_last_name', models.CharField(max_length=100)),
                ('player_nationality', models.CharField(max_length=100)),
                ('current_league', models.CharField(max_length=100)),
                ('current_club', models.CharField(max_length=100)),
                ('current_contract_start_date', models.DateField()),
            ],
        ),
    ]
