# Generated by Django 5.0.3 on 2024-09-11 09:50
from datetime import datetime

from django.db import migrations

from clubstints.models import PlayerProfiles
"""
This method updates the records of players who changed clubs
at the start of the 2024/25 soccer season.
"""
def club_changes_2024(players, new_clubs):
    # New player data
      # Name data
    transferred_players = ["Victor Osimhen", "Habib Diallo", "Wilfried Zaha",
                           "Seko Fofana", "Mbala Nzola", "Amath Ndiaye", "ElBilal Toure"]
      # Club data
    clubs = ["Galatasaray", "Damac FC", "Olympique Lyonnais", "Al-Ettifaq",
             "Lens", "Real Valladolid", "VfB Stuggart"]
      # League data
    leagues = ["Super Lig (Turkey)", "Saudi Pro League (Saudi Arabia)", "Ligue 1 (France)",
               "Saudi Pro League (Saudi Arabia)", "Ligue 1 (France)", "La Liga (Spain)",
               "Bundesliga (Germany)"]
      # Time data
    start_months = [9, 8, 8, 1, 8, 2, 8]
    start_days = [2, 26, 31, 30, 10, 1, 23]
    # Creating 'datetime' objects
    start_dates = []
    for m, d in zip(start_months, start_days):
        new_date = datetime(2024, m, d)
        start_dates.append(new_date)
    # Updating records
    for t, c, l, s in zip(transferred_players, clubs, leagues, start_dates):
        PlayerProfiles.objects.filter(player_name = t).update(current_league = l, 
                                                              current_club = c,
                                                              current_contract_start_date = s)

class Migration(migrations.Migration):

    dependencies = [
        ('clubstints', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(club_changes_2024)
    ]
